# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41fca0c46d5ce62fb90ebb18f142eb0d0df0388b3114d0fcb1ff78ce321fe425416a02c67fe4250db4f0c72e6661a78adde82f25858468c20df485d9b3340372

test:
  secret_key_base: bfaa5d03f12500c24a25675b87ae3d07a6b98479966a2b32cd3be4d449e4a794006f7a2eca9766010b0a9e35f8f00ad98e6dee817d18ddd81a5fd75391ebf9d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
